### PR TITLE
Initial Bluesky support.

### PR DESCRIPTION
**Pull request by qwrrty**
[EDIT: with the latest commits, threading and rendering bugs have been fixed and this appears to be fully functional -- I have started running it every 10 minutes on https://bsky.app/profile/nytdiff.bsky.social]

This PR is not yet ready to merge -- the code is definitely not entirely working yet -- but I thought you would be interested to see where I am with Bluesky support.

Some notes:
* Bluesky requires the client to compose a website preview card, so there's a little extra logic in there to fetch the thumbnail image and such.
* Bluesky replies need to specify a "strong ref" to both the parent article and the root of the thread, and each ref consists of a URI and a CID. So there are four (!) additional data elements that need to be recorded in the database. There might be a more elegant way to do this.
* Images of diffs are not being cropped properly, probably because the switch from PhantomJS to Chrome means they're being rendered differently. I don't have much experience with Selenium and am happy to write this to use a different webdriver if you have a preference.

In its current state, this branch will create Bluesky threads and add followups e.g. "change in URL", "change in abstract" etc. but the Bluesky threads are definitely not being constructed properly, some diffs appear to be getting posted but are not attached to the right article, etc. I will continue to work on that.

Please feel free to make suggestions, or not, as your time permits -- just giving you an update.

### CODE REVIEW

**Comment by qwrrty** [comment]
I see now why my version is screwing up threading so badly: the NYT Top Stories API is returning `short_url: ""` for every article, so every article in the Top Stories feed is getting assigned an article_id of "".

```
$ curl --url-query api-key=xxxxxx https://api.nytimes.com/svc/topstories/v2/home.json | jq .
{
  "status": "OK",
  "copyright": "Copyright (c) 2024 The New York Times Company. All Rights Reserved.",
  "section": "home",
  "last_updated": "2024-03-23T18:11:24-04:00",
  "num_results": 28,
  "results": [
    {
      "section": "world",
      "subsection": "europe",
      "title": "In First Remarks on Attack, Putin Tries to Link Assailants to Ukraine",
      "abstract": "American officials, who have assessed that a branch of the Islamic State was responsible, have voiced concern that the Russian leader could seek to falsely blame Ukraine.",
      "url": "https://www.nytimes.com/2024/03/23/world/europe/moscow-attack-putin.html",
      ...
      "short_url": ""
    },
    ...
```

Is this not the case for you?? I'm very curious why this is happening!

I will try to see whether the `uri` parameter remains stable between article changes.

**Comment by j-e-d** [comment]
They added the uri in 2020 and I've been using that since then, the issue is that the github code has diverged from the production code. 
Before I can push the current code I need to do some clean up because in production I use the same code for NYT and a couple more newspapers. I don't want to upload the code of those because they don't offer an API and I need to scrape the content and the metadata.
Sorry for that.

**Comment by qwrrty** [comment]
Haha! No worries, that's all I needed to know. I hope I'm not making your life more complicated by sending you changes when the github code has already diverged from production :-)

**Comment by qwrrty** [comment]
Hey, I think it's working! https://bsky.app/profile/nytdiff.bsky.social

**Comment by j-e-d** [comment]
Great to see it working!! I will update the current code and merge your changes. Thanks for this.

**Comment by j-e-d** [comment]
I've updated the code to reflect the current production code. I see that the images of the diff after your changes get cut on the left side. Not sure if that is related to the css or selenium. Also check if you can add the alt-text to the bsky images if possible.

**Comment by qwrrty** [comment]
Oh that's exciting, thank you!

I noticed that the diffs are getting truncated on the right hand side, that seems to be something that happened after I deployed to my Debian instance, so I'm wondering if there's some difference in the way headless Chrome is rendering the text on Debian vs. macOS. I will look into it.

And yes, alt text was one of the next things I wanted to add :-)

**Pull request merged**
